meson: Provide missing meson dependency for tests
Currently local meson build fails with error:
"""
../health_metric_config.cpp:5:10: fatal error: nlohmann/json.hpp:
No such file or directory
    5 | #include <nlohmann/json.hpp>
"""
Add missing nlohmann_json dependency to fix the issue.

Tested:
Local build via "meson setup build && cd build && meson compile" now
finishes without errors.

Change-Id: I1f42d6a9c1ddf838a90f7d8b9d880cc4faf7150c
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>